<script>
  let p1 = new Promise((resolve,reject) =>{
    console.log("Promise is pending")
    setTimeout(() =>{
        console.log("I am a promise and I am fulfilled")
        resolve(true)


    }, 5000)
  })

  let p2 = new Promise((resolve, reject) =>{
    console.log("promise is pending")
    setTimeout(() =>{
        console.log("I am a promise and I am rejected")
        reject(new Error("I am an error"))
    }, 5000)
  })
  p1.then((value)=>{
    console.log(value);
  })
 
 p2.catch((error)=>{
    console.log("some error occured in p2");

 })

 // to catch the errors 
 p2.then((value)=>{
    console.log(value)
 },(error)=>{
    console.log(error)
 })


 




 






//    console.log(p1, p2);





</script>